### ISSUE TITLE
Make code PEP8 compliant

### ISSUE THREAD

**Issue by JeffPaine** [frontporchstep/console-clock#1]
For [PEP8](https://www.python.org/dev/peps/pep-0008/) I use the vim plugin https://github.com/nvie/vim-flake8 to give me visual warnings / reminders of formatting errors.

:smile:

**Comment by frontporchstep** [comment]
flake8 consoleclock.py | wc -l
47

yep... Thanks!

**Comment by frontporchstep** [comment]
flake8 consoleclock.py | wc -l 
0

See anything else major that flake8 might not have caught?  Does this plugin generally catch most issues?

**Comment by JeffPaine** [comment]
Looks great man, nice work!

>  Does this plugin generally catch most issues?

It catches the vast majority of formatting issues. It won't catch logic issues like bugs, but I find well formatted code helps make code more readable and thus easier to debug.
